### ISSUE TITLE
CogSci21 Gibsonian Information

### ISSUE THREAD

**Issue by jesparent** [OREL-group/Developmental-AI#2]
- [x] submit draft

- [x] review

**Comment by Athene-ai** [comment]
Which is the assignment #2?

Daniela

**Comment by jesparent** [comment]
I'm not sure if there's anything left to review at this point, it may be complete. I believe it has fully been submitted now, yes @balicea  ?

**Comment by Orthogonal-Research-Lab** [comment]
Yes. It is fully submitted, and we should hear back in mid-April. Either way, we will preprint and go from there.

**Comment by Athene-ai** [comment]
I see.

Thanks for the  explanation  :)

Daniela

Il giorno 07:52 Lun 15/Feb/2021 Orthogonal Research and Education
Laboratory <notifications@github.com> ha scritto:

**Comment by jesparent** [comment]
Not accepted - but paper is being repurposed, maybe for BICA
